### ISSUE TITLE
Wtczka

### ISSUE THREAD

**Issue by kashkash18** [paneee/RepoFF#1]
Bardzo się cieszę że wtyczka powstała i mam nadzieję że będzie aktualizowana. Czy istnieje szansa by ją pokatalogowac ?? Np na magazyny , mecze , dokumenty itd ??

**Comment by paneee** [comment]
Miło mi, że się podoba. W miarę możliwości czasowych planuję ją rozwijać.
Co do katalogowania to w najbliższej przyszłości nie planuję, aczkolwiek nie mówię nie.
Najpierw chcę spróbować dorobić player do radia weszło i zapinamypasy.

**Comment by kashkash18** [comment]
Ooooo i to jest bardzo dobry pomysł :) Powodzenia oby tak dalej

**Comment by rafciu27** [comment]
Witam. Mam problem z instalacją wtyczki na Kodi 16. Podczas próby instalacji wywala mi komunikat "nieudana instalacja z pliku zip". Czy jest możliwość rozwiązania tego problemu czy po prostu wtyczka nie obsługuje starszych wersji kodi? Pozdrawiam

**Comment by paneee** [comment]
Podałbyś szczegóły z log-u? (plik Kodi.log)

**Comment by rafciu27** [comment]
http://paste.kodi.tv/ojibidimuk

**Comment by paneee** [comment]
W zamieszczonym przez Ciebie zrzucie nie ma nic o o wtyczce MeczReplay.

**Comment by rafciu27** [comment]
Właśnie nie wiem dlaczego, przy próbie instalacji mimo "nieudanej próby instalacji" ani śladu działania w logach. Sprawdzałem jeszcze parę razy i nic. Trudno się mówi ;)

**Comment by rafciu27** [comment]
Źle się wcześniej wyraziłem, nie wtyczki tylko repozytorium. Ale pewnie to nie wielka różnica w tym kontekście.

**Comment by kashkash18** [comment]
Witam , w wtyczce pokazuje tylko 57 pozycji . Czy da się coś z tym zrobić ?? Na dziś dzień ostatnia pozycja to MS Uruwaj - Arabia 20.06

**Comment by paneee** [comment]
Cześć, w pliku
...\plugin.video.meczreplay-0.0.3.zip\plugin.video.meczreplay-0.0.3\resources\lib\meczreplay.py
w 23 linii, jest link do strony, która jest parsowana:
`html = urllib.urlopen('https://meczreplay.blogspot.com/search?max-results=50')`
Możesz tą linię zmienić na:
`html = urllib.urlopen('https://meczreplay.blogspot.com/search?updated-max=2018-06-22T00:22:00-07:00&max-results=200&start=50&by-date=false')`
czyli kolejną podstronę.

**Comment by kashkash18** [comment]
W takim rozwiązaniu lista poszerza się do 70 pozycji. Bardziej miałem na myśli opcje następnej strony. Nie jest to jakieś mega ważne , ale posiadasz tam fajne rzeczy do których nawet czesto wracam .

**Comment by kashkash18** [comment]
Witam , i jest jakaś szansa na dodanie stronicowania ??

**Comment by paneee** [comment]
Jest szansa. W najbliższym czasie na to popatrzę. 
Do piątku powinienem dorobić.

**Comment by kashkash18** [comment]
Super , bardzo Ci dziękuję. Działa elegancko. Przydało by się jeszcze katalogowanie ale to pewnie sporo roboty. A można ewentualnie dodać jeszcze opcje szukaj tak by przeszukiwał całe zasoby ??

**Comment by paneee** [comment]
W miarę możliwości czasowych, postaram się coś podziałać w tych tematach w najbliższym czasie.

**Comment by kashkash18** [comment]
Super , dzięki wielkie :)

**Comment by kashkash18** [comment]
No Panie teraz to jest mistrzostwo świata :) Jeszcze raz bardzo Ci dziękuję . Szacunek

**Comment by kashkash18** [comment]
Jeszcze jedno pytanie , wg wtyczki i strony pierwszy materiał został dodany 25.02.2018 , jest szansa by przywrócić materiały z poprzednich lat ?? Czy była jakaś awaria i poszło ...

**Comment by paneee** [comment]
Miło mi, że Ci pasuje.
Co do materiałów, to wtyczka prezentuje tylko to co jest na stronie, więc nie mam skąd wziąć linków do poprzednich magazynów. Z tego co wiem to koledze tworzącemu stronę poprzedni hosting usunął ją i poszło...
Jak coś to możesz się z nim kontaktować i zapytać, czy ma gdzieś źródła.

**Comment by kashkash18** [comment]
A już myślałem że paneee to szumek :) Napiszę i zobaczymy czy uda się coś zdziałać.

**Comment by paneee** [comment]
Nie, też musiałem do niego pisać w temacie, czy nie ma nic przeciwko upublicznieniu wtyczki :)

**Comment by kashkash18** [comment]
Siemanko , to znowu ja ;) Dasz radę w wolnej chwili rzucić okiem na wtyczkę ?? Chodzi o to że w najnowszych nazwy wydarzeń są inne niż w konkretnych kategoriach . Np. None gala , None walka , None magazyn

**Comment by paneee** [comment]
Cześć   Poprawiłem. :)  
            
          
     
      
       
        Dnia 2 grudnia 2018 18:52 kashkash18 &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Siemanko , to znowu ja ;) Dasz radę w wolnej chwili rzucić okiem na wtyczkę ?? Chodzi o to że w najnowszych nazwy wydarzeń są inne niż w konkretnych kategoriach . Np. None gala , None walka , None magazyn
